_wandb:
    value:
        cli_version: 0.19.3
        code_path: code/engiopt/gan_2d.py
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 49
                - 51
                - 55
            "2":
                - 1
                - 49
                - 51
                - 55
            "3":
                - 13
                - 14
                - 16
                - 23
                - 55
            "4": 3.12.2
            "5": 0.19.3
            "8":
                - 2
                - 5
            "12": 0.19.3
            "13": linux-x86_64
algo:
    value: gan_2d
b1:
    value: 0.5
b2:
    value: 0.999
batch_size:
    value: 256
latent_dim:
    value: 100
lr:
    value: 0.0003
n_cpu:
    value: 8
n_epochs:
    value: 300
problem_id:
    value: draw_circle_v0
sample_interval:
    value: 400
save_model:
    value: false
seed:
    value: 1
track:
    value: true
wandb_entity:
    value: null
wandb_project:
    value: engiopt
